import { AnchorProvider, Program, Wallet } from "@coral-xyz/anchor";
import pkg from "@coral-xyz/anchor";
const { BN } = pkg;
import {
  Connection,
  PublicKey,
  SystemProgram,
  Keypair,
} from "@solana/web3.js";
import * as fs from "fs";
import * as path from "path";
import { fileURLToPath } from "url";
import * as chai from "chai";
import dotenv from "dotenv";

const expect = chai.expect;
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Load environment variables from the main .env file
dotenv.config({ path: path.join(__dirname, "../.env") });

// Load config
const config = JSON.parse(
  fs.readFileSync(path.join(__dirname, "../devnet-config.json"), "utf-8")
);

// Load IDL (generated by Anchor build)
const idlPath = path.join(__dirname, "../target/idl/irma.json");
if (!fs.existsSync(idlPath)) {
  throw new Error(
    "Missing IDL at target/idl/irma.json. Run `anchor build` (or `anchor idl build -o target/idl`) in the irma/ directory before running tests."
  );
}
const idl = JSON.parse(fs.readFileSync(idlPath, "utf-8"));

// Use program ID from IDL (which should match the declare_id! in Rust code)
const PROGRAM_ID = new PublicKey(idl.address);
console.log("🆔 Using Program ID from IDL:", PROGRAM_ID.toBase58());

/**
 * Helper function to setup connection, provider, and program
 */
async function setupTestEnvironment() {
  const rpcUrl =
    process.env.ANCHOR_PROVIDER_URL ||
    process.env.SOLANA_RPC_URL ||
    "https://api.devnet.solana.com";
  const commitment = (process.env.ANCHOR_COMMITMENT ||
    process.env.SOLANA_COMMITMENT ||
    "confirmed") as any;

  const connection = new Connection(rpcUrl, commitment);

  let keypair: Keypair;

  if (process.env.SOLANA_PRIVATE_KEY) {
    try {
      const privateKeyArray = JSON.parse(process.env.SOLANA_PRIVATE_KEY);
      keypair = Keypair.fromSecretKey(new Uint8Array(privateKeyArray));
    } catch (error) {
      keypair = Keypair.generate();
    }
  } else {
    keypair = Keypair.generate();
  }

  const wallet = new Wallet(keypair);
  const provider = new AnchorProvider(connection, wallet, { commitment });
  const program = new Program(idl, provider);

  return {
    connection,
    provider,
    program,
    payer: provider.wallet.publicKey,
    wallet,
  };
}

/**
 * Helper function to derive PDAs
 */
function derivePdas(programId: PublicKey) {
  const [statePda] = PublicKey.findProgramAddressSync(
    [Buffer.from("state_v5")],
    programId
  );

  const [corePda] = PublicKey.findProgramAddressSync(
    [Buffer.from("core_v5")],
    programId
  );

  return { statePda, corePda };
}

/**
 * Helper function to get prices for a reserve
 */
async function getPricesForReserve(
  reserve: string,
  program: Program,
  statePda: PublicKey,
  corePda: PublicKey,
  payer: PublicKey
) {
  console.log(
    "\n📊 Getting prices for reserve:",
    reserve,
    "\n==============================\n"
  );
  const pricesResult = await program.methods
    .getPrices(reserve)
    .accounts({
      state: statePda,
      irmaAdmin: payer,
      core: corePda,
      systemProgram: SystemProgram.programId,
    })
    .simulate();

  // Look for the "Program return" line in the raw logs
  const returnLine = pricesResult.raw.find((line: string) =>
    line.includes("Program return:")
  );

  if (returnLine) {
    const base64Data = returnLine.split(" ").pop();
    if (base64Data) {
      const decodedData = Buffer.from(base64Data, "base64");

      if (decodedData.length >= 16) {
        const mintPrice = decodedData.readDoubleLE(0);
        const redemptionPrice = decodedData.readDoubleLE(8);
        console.log("📊 Mint Price:", mintPrice);
        console.log("📊 Redemption Price:", redemptionPrice);
        return { mintPrice, redemptionPrice };
      }
    }
  }
  return null;
}

/**
 * Test Suite: Limit Orders
 */
describe("Limit Orders Tests", () => {
  let connection: Connection;
  let provider: AnchorProvider;
  let program: Program;
  let payer: PublicKey;
  let wallet: Wallet;
  let statePda: PublicKey;
  let corePda: PublicKey;

  before("Setup test environment", async () => {
    const env = await setupTestEnvironment();
    connection = env.connection;
    provider = env.provider;
    program = env.program;
    payer = env.payer;
    wallet = env.wallet;

    const pdas = derivePdas(PROGRAM_ID);
    statePda = pdas.statePda;
    corePda = pdas.corePda;

    console.log("\n🌐 Test Environment Setup:");
    console.log(`   Payer: ${payer.toBase58()}`);
    console.log(`   State PDA: ${statePda.toBase58()}`);
    console.log(`   Core PDA: ${corePda.toBase58()}\n`);

    // Check balance
    const balance = await connection.getBalance(payer);
    console.log("💰 Current balance:", balance / 1e9, "SOL\n");

    if (balance < 0.5e9) {
      console.warn(
        "⚠️ Low balance detected. Some tests may fail due to insufficient funds."
      );
    }
  });

  describe("place_limit_order", () => {
    it("should place a limit order on the first reserve", async function () {
      this.timeout(30000);

      const knownSymbols = Object.values(config.tokens).map(
        (t: any) => t.name
      );
      if (knownSymbols.length === 0) {
        console.log("⚠️ No reserves configured. Skipping test.");
        this.skip();
        return;
      }

      const reserve = knownSymbols[0];
      console.log(`\n🎯 Placing limit order for reserve: ${reserve}`);

      // Generate a keypair for the limit order
      const limitOrderKeypair = Keypair.generate();
      const limitOrderPubkey = limitOrderKeypair.publicKey;

      console.log(`   Limit Order Account: ${limitOrderPubkey.toBase58()}`);

      try {
        // Call place_limit_order instruction
        // Note: This is a simplified version without all the required remaining accounts
        // In a real scenario, you would need to pass all necessary DLMM accounts
        const tx = await program.methods
          .placeLimitOrder(
            reserve, // symbol
            limitOrderPubkey, // limit_order
            false, // is_ask_side (false = bid side)
            1000, // bin_id (price level)
            new BN(1_000_000) // amount
          )
          .accounts({
            state: statePda,
            irmaAdmin: payer,
            core: corePda,
            systemProgram: SystemProgram.programId,
          })
          .transaction();

        // We'll just construct the transaction and check it builds correctly
        // In a full devnet test, you would send this transaction
        expect(tx).to.be.an("object");
        console.log("✅ place_limit_order transaction constructed successfully");
      } catch (error: any) {
        console.warn(
          "Skipping: place_limit_order transaction construction requires DLMM remaining accounts / devnet pool setup.",
          error?.message
        );
        this.skip();
      }
    });

    it("should construct a transaction even with an unknown reserve (validation occurs on-chain)", async function () {
      this.timeout(30000);

      const invalidReserve = "NONEXISTENT_TOKEN";
      const limitOrderKeypair = Keypair.generate();

      console.log("\n🧪 Testing invalid reserve rejection:");
      console.log(`   Reserve: ${invalidReserve}`);

      try {
        const tx = await program.methods
          .placeLimitOrder(
            invalidReserve,
            limitOrderKeypair.publicKey,
            false,
            1000,
            new BN(1_000_000)
          )
          .accounts({
            state: statePda,
            irmaAdmin: payer,
            core: corePda,
            systemProgram: SystemProgram.programId,
          })
          .transaction();

        expect(tx).to.be.an("object");
        console.log(
          "ℹ️ Transaction constructed; reserve validation happens on-chain during simulation/execution"
        );
      } catch (error: any) {
        console.warn(
          "Skipping: on-chain reserve validation requires full DLMM accounts to simulate/execute.",
          error?.message
        );
        this.skip();
      }
    });

    it("should support both ask and bid sides", async function () {
      this.timeout(30000);

      const knownSymbols = Object.values(config.tokens).map(
        (t: any) => t.name
      );
      if (knownSymbols.length === 0) {
        this.skip();
        return;
      }

      const reserve = knownSymbols[0];
      console.log("\n🧪 Testing limit order sides:");

      // Test ask side
      const askOrderKeypair = Keypair.generate();
      console.log(`   Ask side limit order: ${askOrderKeypair.publicKey.toBase58()}`);

      try {
        const askTx = await program.methods
          .placeLimitOrder(
            reserve,
            askOrderKeypair.publicKey,
            true, // is_ask_side = true
            2000,
            new BN(500_000)
          )
          .accounts({
            state: statePda,
            irmaAdmin: payer,
            core: corePda,
            systemProgram: SystemProgram.programId,
          })
          .transaction();

        expect(askTx).to.be.an("object");
        console.log("   ✅ Ask side order constructed");
      } catch (error) {
        console.log("   ℹ️ Ask side test note:", error.message);
      }

      // Test bid side
      const bidOrderKeypair = Keypair.generate();
      console.log(`   Bid side limit order: ${bidOrderKeypair.publicKey.toBase58()}`);

      try {
        const bidTx = await program.methods
          .placeLimitOrder(
            reserve,
            bidOrderKeypair.publicKey,
            false, // is_ask_side = false
            1000,
            new BN(500_000)
          )
          .accounts({
            state: statePda,
            irmaAdmin: payer,
            core: corePda,
            systemProgram: SystemProgram.programId,
          })
          .transaction();

        expect(bidTx).to.be.an("object");
        console.log("   ✅ Bid side order constructed");
      } catch (error) {
        console.log("   ℹ️ Bid side test note:", error.message);
      }
    });
  });

  describe("cancel_limit_order", () => {
    it("should cancel a limit order", async function () {
      this.timeout(30000);

      const limitOrderKeypair = Keypair.generate();
      const knownSymbols = Object.values(config.tokens).map(
        (t: any) => t.name
      );

      if (knownSymbols.length === 0) {
        this.skip();
        return;
      }

      const reserve = knownSymbols[0];

      console.log("\n🧪 Testing cancel_limit_order:");
      console.log(`   Reserve: ${reserve}`);
      console.log(
        `   Limit Order: ${limitOrderKeypair.publicKey.toBase58()}`
      );

      try {
        const tx = await program.methods
          .cancelLimitOrder(
            reserve,
            limitOrderKeypair.publicKey,
            [1000, 1001] // bin_ids
          )
          .accounts({
            state: statePda,
            irmaAdmin: payer,
            core: corePda,
            systemProgram: SystemProgram.programId,
          })
          .transaction();

        expect(tx).to.be.an("object");
        console.log("✅ cancel_limit_order transaction constructed successfully");
      } catch (error) {
        console.log("ℹ️ cancel_limit_order test note:", error.message);
      }
    });

    it("should handle multiple bin ids in cancel order", async function () {
      this.timeout(30000);

      const limitOrderKeypair = Keypair.generate();
      const knownSymbols = Object.values(config.tokens).map(
        (t: any) => t.name
      );

      if (knownSymbols.length === 0) {
        this.skip();
        return;
      }

      const reserve = knownSymbols[0];

      console.log("\n🧪 Testing cancel with multiple bin ids:");
      console.log(`   Bin IDs: [999, 1000, 1001, 1002]`);

      try {
        const tx = await program.methods
          .cancelLimitOrder(
            reserve,
            limitOrderKeypair.publicKey,
            [999, 1000, 1001, 1002] // Multiple bin_ids
          )
          .accounts({
            state: statePda,
            irmaAdmin: payer,
            core: corePda,
            systemProgram: SystemProgram.programId,
          })
          .transaction();

        expect(tx).to.be.an("object");
        console.log(
          "✅ cancel_limit_order with multiple bins constructed successfully"
        );
      } catch (error) {
        console.log("ℹ️ Multiple bin ids test note:", error.message);
      }
    });

    it("should handle empty bin ids list", async function () {
      this.timeout(30000);

      const limitOrderKeypair = Keypair.generate();
      const knownSymbols = Object.values(config.tokens).map(
        (t: any) => t.name
      );

      if (knownSymbols.length === 0) {
        this.skip();
        return;
      }

      const reserve = knownSymbols[0];

      console.log("\n🧪 Testing cancel with empty bin ids:");

      try {
        const tx = await program.methods
          .cancelLimitOrder(
            reserve,
            limitOrderKeypair.publicKey,
            [] // Empty bin_ids
          )
          .accounts({
            state: statePda,
            irmaAdmin: payer,
            core: corePda,
            systemProgram: SystemProgram.programId,
          })
          .transaction();

        expect(tx).to.be.an("object");
        console.log("✅ cancel_limit_order with empty bins constructed successfully");
      } catch (error) {
        console.log("ℹ️ Empty bin ids test note:", error.message);
      }
    });
  });

  describe("close_limit_order_if_empty", () => {
    it("should close an empty limit order", async function () {
      this.timeout(30000);

      const limitOrderKeypair = Keypair.generate();

      console.log("\n🧪 Testing close_limit_order_if_empty:");
      console.log(`   Limit Order: ${limitOrderKeypair.publicKey.toBase58()}`);

      try {
        const tx = await program.methods
          .closeLimitOrderIfEmpty(limitOrderKeypair.publicKey)
          .accounts({
            state: statePda,
            irmaAdmin: payer,
            core: corePda,
            systemProgram: SystemProgram.programId,
          })
          .transaction();

        expect(tx).to.be.an("object");
        console.log(
          "✅ close_limit_order_if_empty transaction constructed successfully"
        );
      } catch (error) {
        console.log(
          "ℹ️ close_limit_order_if_empty test note:",
          error.message
        );
      }
    });

    it("should handle multiple close operations", async function () {
      this.timeout(30000);

      console.log("\n🧪 Testing multiple close operations:");

      for (let i = 0; i < 3; i++) {
        const limitOrderKeypair = Keypair.generate();

        try {
          const tx = await program.methods
            .closeLimitOrderIfEmpty(limitOrderKeypair.publicKey)
            .accounts({
              state: statePda,
              irmaAdmin: payer,
              core: corePda,
              systemProgram: SystemProgram.programId,
            })
            .transaction();

          expect(tx).to.be.an("object");
          console.log(
            `   ✅ Close operation ${i + 1}: Transaction constructed`
          );
        } catch (error) {
          console.log(`   ℹ️ Close operation ${i + 1} note:`, error.message);
        }
      }
    });
  });

  describe("Limit Orders Integration", () => {
    it("should place and cancel orders in sequence", async function () {
      this.timeout(60000);

      const knownSymbols = Object.values(config.tokens).map(
        (t: any) => t.name
      );

      if (knownSymbols.length === 0) {
        this.skip();
        return;
      }

      const reserve = knownSymbols[0];

      console.log("\n🧪 Testing sequential place and cancel:");
      console.log(`   Reserve: ${reserve}\n`);

      // Step 1: Place a limit order
      const limitOrderKeypair = Keypair.generate();
      console.log(`   Step 1: Placing limit order...`);

      try {
        const placeTx = await program.methods
          .placeLimitOrder(
            reserve,
            limitOrderKeypair.publicKey,
            false, // bid side
            1000,
            new BN(1_000_000)
          )
          .accounts({
            state: statePda,
            irmaAdmin: payer,
            core: corePda,
            systemProgram: SystemProgram.programId,
          })
          .transaction();

        expect(placeTx).to.be.an("object");
        console.log(`   ✅ Limit order placed (transaction constructed)`);

        // Step 2: Cancel the same order
        console.log(`   Step 2: Canceling limit order...`);

        const cancelTx = await program.methods
          .cancelLimitOrder(
            reserve,
            limitOrderKeypair.publicKey,
            [1000]
          )
          .accounts({
            state: statePda,
            irmaAdmin: payer,
            core: corePda,
            systemProgram: SystemProgram.programId,
          })
          .transaction();

        expect(cancelTx).to.be.an("object");
        console.log(`   ✅ Limit order canceled (transaction constructed)`);

        // Step 3: Close the empty order
        console.log(`   Step 3: Closing empty limit order...`);

        const closeTx = await program.methods
          .closeLimitOrderIfEmpty(limitOrderKeypair.publicKey)
          .accounts({
            state: statePda,
            irmaAdmin: payer,
            core: corePda,
            systemProgram: SystemProgram.programId,
          })
          .transaction();

        expect(closeTx).to.be.an("object");
        console.log(`   ✅ Empty limit order closed (transaction constructed)`);

        console.log(
          `\n✅ Sequence completed: place → cancel → close\n`
        );
      } catch (error) {
        console.log(
          "ℹ️ Sequential test note: Full integration testing requires DLMM accounts"
        );
        console.log(`   Error: ${error.message}`);
      }
    });

    it("should handle concurrent order placements", async function () {
      this.timeout(60000);

      const knownSymbols = Object.values(config.tokens).map(
        (t: any) => t.name
      );

      if (knownSymbols.length === 0) {
        this.skip();
        return;
      }

      const reserve = knownSymbols[0];
      const orderCount = 3;

      console.log(
        `\n🧪 Testing concurrent order placements (${orderCount} orders):`
      );

      try {
        const orderKeypairs = Array.from({ length: orderCount }, () =>
          Keypair.generate()
        );

        // Construct all transactions
        const transactions = await Promise.all(
          orderKeypairs.map((keypair, index) =>
            program.methods
              .placeLimitOrder(
                reserve,
                keypair.publicKey,
                index % 2 === 0, // alternate between ask and bid
                1000 + index * 10,
                new BN(500_000)
              )
              .accounts({
                state: statePda,
                irmaAdmin: payer,
                core: corePda,
                systemProgram: SystemProgram.programId,
              })
              .transaction()
          )
        );

        expect(transactions).to.have.lengthOf(orderCount);
        console.log(`✅ Successfully constructed ${orderCount} limit orders`);

        for (let i = 0; i < orderCount; i++) {
          console.log(
            `   Order ${i + 1}: ${orderKeypairs[i].publicKey.toBase58()}`
          );
        }
      } catch (error) {
        console.log("ℹ️ Concurrent test note:", error.message);
      }
    });
  });

  describe("Edge Cases", () => {
    it("should handle maximum bin id values", async function () {
      this.timeout(30000);

      const knownSymbols = Object.values(config.tokens).map(
        (t: any) => t.name
      );

      if (knownSymbols.length === 0) {
        this.skip();
        return;
      }

      const reserve = knownSymbols[0];
      const limitOrderKeypair = Keypair.generate();

      console.log("\n🧪 Testing with maximum bin id values:");
      console.log(`   Using high bin ID: 2147483647 (max i32)`);

      try {
        const tx = await program.methods
          .placeLimitOrder(
            reserve,
            limitOrderKeypair.publicKey,
            false,
            2147483647, // max i32 value
            new BN(1_000_000)
          )
          .accounts({
            state: statePda,
            irmaAdmin: payer,
            core: corePda,
            systemProgram: SystemProgram.programId,
          })
          .transaction();

        expect(tx).to.be.an("object");
        console.log("✅ Max bin id value accepted");
      } catch (error) {
        console.log("ℹ️ Max bin id test note:", error.message);
      }
    });

    it("should handle minimum bin id values", async function () {
      this.timeout(30000);

      const knownSymbols = Object.values(config.tokens).map(
        (t: any) => t.name
      );

      if (knownSymbols.length === 0) {
        this.skip();
        return;
      }

      const reserve = knownSymbols[0];
      const limitOrderKeypair = Keypair.generate();

      console.log("\n🧪 Testing with minimum bin id values:");
      console.log(`   Using low bin ID: -2147483648 (min i32)`);

      try {
        const tx = await program.methods
          .placeLimitOrder(
            reserve,
            limitOrderKeypair.publicKey,
            false,
            -2147483648, // min i32 value
            new BN(1_000_000)
          )
          .accounts({
            state: statePda,
            irmaAdmin: payer,
            core: corePda,
            systemProgram: SystemProgram.programId,
          })
          .transaction();

        expect(tx).to.be.an("object");
        console.log("✅ Min bin id value accepted");
      } catch (error) {
        console.log("ℹ️ Min bin id test note:", error.message);
      }
    });

    it("should handle large amount values", async function () {
      this.timeout(30000);

      const knownSymbols = Object.values(config.tokens).map(
        (t: any) => t.name
      );

      if (knownSymbols.length === 0) {
        this.skip();
        return;
      }

      const reserve = knownSymbols[0];
      const limitOrderKeypair = Keypair.generate();

      console.log("\n🧪 Testing with large amount values:");
      const largeAmount = new BN("18446744073709551615"); // max u64
      console.log(`   Using large amount: ${largeAmount.toString()}`);

      try {
        const tx = await program.methods
          .placeLimitOrder(
            reserve,
            limitOrderKeypair.publicKey,
            false,
            1000,
            largeAmount
          )
          .accounts({
            state: statePda,
            irmaAdmin: payer,
            core: corePda,
            systemProgram: SystemProgram.programId,
          })
          .transaction();

        expect(tx).to.be.an("object");
        console.log("✅ Large amount value accepted");
      } catch (error) {
        console.log("ℹ️ Large amount test note:", error.message);
      }
    });

    it("should handle zero amount", async function () {
      this.timeout(30000);

      const knownSymbols = Object.values(config.tokens).map(
        (t: any) => t.name
      );

      if (knownSymbols.length === 0) {
        this.skip();
        return;
      }

      const reserve = knownSymbols[0];
      const limitOrderKeypair = Keypair.generate();

      console.log("\n🧪 Testing with zero amount:");

      try {
        const tx = await program.methods
          .placeLimitOrder(
            reserve,
            limitOrderKeypair.publicKey,
            false,
            1000,
            new BN(0) // zero amount
          )
          .accounts({
            state: statePda,
            irmaAdmin: payer,
            core: corePda,
            systemProgram: SystemProgram.programId,
          })
          .transaction();

        expect(tx).to.be.an("object");
        console.log("✅ Zero amount accepted by transaction builder");
        console.log(
          "   Note: On-chain validation may reject this during execution"
        );
      } catch (error) {
        console.log("ℹ️ Zero amount test note:", error.message);
      }
    });
  });
});
